version: '{build}'
skip_tags: false
shallow_clone: true
environment:
  matrix:
  - SCRIPT: contrib\appveyor-mingw.bat
    RELEASE_ARTIFACT: true
  - SCRIPT: contrib\appveyor-msvc.bat
  - SCRIPT: contrib\appveyor-mingw-qt53.bat
configuration:
- RelWithDebInfo
matrix:
  fast_finish: true
install:
- ps: (new-object net.webclient).DownloadFile('https://ci.appveyor.com/api/projects/neovim/neovim/artifacts/build/Neovim.exe?tag=nightly&job=Configuration%3A%20MINGW_64', 'Neovim.exe')
- start "" /wait Neovim.exe /S
- dir C:\Program Files (x86)\Neovim\bin
- nvim --version
build_script:
- cmd: '%SCRIPT%'
- cmd: cmake --build . --target test
artifacts:
- path: INSTALL
  name: neovim-qt
deploy:
  - provider: GitHub
    description: Automated builds (Appveyor)
    release: $(appveyor_repo_tag_name)
    auth_token:
      secure: Hx2tU6GZPZNB6qGjHcIqa1tEm8fVGXZUVfXyjboVrPcmA9OWMTXhLxayDzMMl3kD
    artifact: neovim-qt.zip
    prerelease: false
    on:
      appveyor_repo_tag: true
      configuration: RelWithDebInfo
      release_artifact: true
